version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/native/rhai_rustler"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/native/test_dylib_module"
    schedule:
      interval: "daily"
